name: flutter_social_media_v1
description: Flutter Social Media Mobile Application

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.13.1
  firebase_auth: ^4.6.0

  google_sign_in: ^6.1.0

  flutter_dotenv: ^5.1.0
  dio: ^5.1.2
  provider: ^6.0.5
  go_router: ^7.1.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  flutter_image_slideshow: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true