name: flutter_social_media_v1
description: Flutter Social Media Mobile Application

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.0
  firebase_messaging: ^14.6.2

  # Notification
  flutter_local_notifications: ^14.1.1

  # Social SignIn
  google_sign_in: ^6.1.0

  # Networking
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1

  # Route
  go_router: ^8.1.0

  # State Management
  provider: ^6.0.5

  # Dependency Injection
  get_it: ^7.6.0

  # Local Storage
  flutter_secure_storage: ^8.0.0

  # Image Slider
  flutter_image_slideshow: ^0.1.5

  # Image Picker
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true